### ISSUE TITLE
reference 翻译问题

### ISSUE THREAD

**Issue by 3Xpl0it3r** [rust-lang-cn/nomicon-zh-Hans#11]
A reference cannot outlive its referent
-* 一个引用的生命周期不能超过其所有者的生命周期
-* 一个可变的引用不能被别名
+* 一个引用的生命周期不能超过它所引用对象的生命周期
+* 一个可变的引用不能有别名

超过其所有者在rust里面有特色含义，owner， 是不是会有点歧义？会不会错误的理解成这个引用变量本身 ？
 
 let's use the next section to discuss what aliasing is in general,
-在我们等待 Rust 的设计者明确他们语言的语义时，让我们用下一节来讨论什么是一般的别名，以及它为什么重要。
+在我们等待 Rust 的设计者明确他们语言的语义时，让我们用下一节来讨论下在一般场景下别名到底是什么，以及它为什么重要。

in general 在一般场景下，一般情况下，是不是会更合理点？

**Comment by PureWhiteWu** [comment]
感谢指出，是否方便提一个 PR 呢？

**Comment by PureWhiteWu** [comment]
fixed by #13
