### ISSUE TITLE
欢迎加入 rust-lang-cn 组织

### ISSUE THREAD

**Issue by aaranxu** [rust-lang-cn/nomicon-zh-Hans#12]
我们组织正准备翻译 nomicon 这本书，我们在之前一个译本也[发起邀请](https://github.com/tjxing/rustonomicon_zh-CN/issues/2)，刚搜索到您这边有一个新的翻译版本，而且翻译得很好。

rust-lang-cn 组织是个开源组织，相应的网站 <https://rustwiki.org> 也是非营利性网站，我们的目标是完善 Rust 的中文资源，特别是 Rust 官方的文档等资料，开源、无私、分享、互助是我们的理念，我们希望 Rust 相关的中文知识库可以持续地良性维护和传承下去。为此特别邀请您加入到我组织，共同管理和维护组织，目前组织已有十多人，其中三人是所有者，若是您有兴趣和精力，我也可邀请您成为组织的所有者，期待您的加入~

**Comment by PureWhiteWu** [comment]
你好，久闻大名了，很荣幸能收到邀请，我十分愿意加入贵组织。
贵组织翻译的书籍质量很高，十分有帮助，非常感谢你们的付出。
后续我需要做什么呀？

**Comment by aaranxu** [comment]
我邀请进入组织里面啊，其实要做的就是统一在 GitHub 组织上一起维护相关的资源，个人是建议文档的仓库都放到 *rust-lang-cn* 组织下，另外将文档放到 *https://rustwiki.org* 下，其他的操作和更新都基本和之前一样。

**Comment by aaranxu** [comment]
目前 Rust 中文翻译项目组织全部就包含 3 部分内容：

- *rust-lang-cn* GitHub 组织以及本组织下的所有资料文档；
- *rustwiki.org* 网站的域名和服务器；
- Rust 翻译小组 QQ 群 716348056（注意进群需提供 GitHub 用户名）。

其中 *rust-lang-cn* 的所有资料内容都是开源的形式提供，一般是 CC0 协议（公有领域作品）或遵循 Rust 官方文档的原有协议（一般是 MIT 或 Apache 2.0 协议），这些资源放到组织的初衷一方面是确保资源的持续维护（不因某个人离开而导致资源无法联系到所有者了），另一方面是尽可能让 Rust 资源能够像英文那样规范化起来管理。

而网站方面目前暂由我来管理，我的想法也是将网站的域名让组织核心成员共同来管理，服务器也计划未来用上组织的共有服务器资源，核心在于域名信息（服务器用哪个对网站影响不大），也需让服务器信息能够持续维护。如果您有好的社区管理资产的方式，也欢迎进一步交流，以便找到最好的开源组织的资产管理方式。

最后的翻译小组 QQ 群由[张汉东](https://github.com/orgs/rust-lang-cn/people/ZhangHanDong)创建，小组主要是讨论 Rust 翻译的事宜。

**Comment by aaranxu** [comment]
目前 *rust-lang-cn* 存放的官方文档有一些[约定](https://rustwiki.org/faq/#rust-zhong-wen-fan-yi-xiang-mu-zu-dui-fan-yi-wen-dang-you-shi-yao-yue-ding)，主要是对仓库名都改成官方仓库名加上 *-cn* 后缀，再加上一个简要的中文翻译说明，而其他的内容原则上和原版的保持一致，几乎不加上任何其他信息。

因为 *rust-lang-cn* 组织的理念是开源、共享、无私、互助，所以组织里面的所有资源均毫无保留地以开源形式奉献出去，后续我们更新的内容都继续遵循我们的理念和开源的相关约定。

**Comment by aaranxu** [comment]
因为 *rust-lang-cn* 组织里面的资源比较多，所以里面的资源维护是有划分不同人来跟进的，我个人是重点维护 *book*（《Rust 程序设计语言》） 和 *Rust By Example*（《通过例子学 Rust》） 这两本书，[David](https://github.com/wendajiang) 目前维护的是 *rustdoc Book*（《rustdoc 手册》），还有组织的其他成员也会不定期更新相关的文档或资料。

在您参与进来后，可重点维护 *Rustonomicon*（《Rust 秘典》），当然若是还有精力，也欢迎维护其他的手册。

非常欢迎和期待您的加入！

**Comment by aaranxu** [comment]
因为 *rust-lang-cn* 组织里面的资源比较多，所以里面的资源维护是有划分不同人来跟进的，其他我个人是重点维护 *book*（《Rust 程序设计语言》） 和 *Rust By Example*（《通过例子学 Rust》） 这两本书，[David](https://github.com/wendajiang) 目前维护的是 *rustdoc Book*（《rustdoc 手册》），还有组织的其他成员也会不定期更新相关的文档或资料。

在您参与进来后，可重点维护 *Rustonomicon*（《Rust 秘典》），当然若是还有精力，也欢迎维护其他的手册。

非常欢迎和期待您的加入！

**Comment by PureWhiteWu** [comment]
好的，我把这个 repo transfer 到 rust-lang-cn 这个组织吧。

**Comment by PureWhiteWu** [comment]
服务器目前这本书是直接托管于阿里云 OSS + CDN 的，我也有一个 2C4G 的服务器闲置可以用。
部署方式的话，后续我们可以微信上沟通一下。

**Comment by aaranxu** [comment]
好的，你有在 Q 群上不

**Comment by aaranxu** [comment]
太好了，欢迎👏
