### ISSUE TITLE
捉一个翻译bug，虚拟语气的问题

### ISSUE THREAD

**Issue by beeplin** [rust-lang-cn/nomicon-zh-Hans#16]
这里翻译的不对。could是虚拟语气不是过去式。意思是，下面的例子本来应该可以编译的，但现在还不行。

The following could also compile:
比如以下的例子，曾经是可以编译成功的：

enum Void {}

let res: Result<u32, Void> = Ok(0);

// 不存在 Err 的情况，所以 Ok 实际上永远都能匹配成功
let Ok(num) = res;

但现在，已经不让这么玩儿了。

**Comment by PureWhiteWu** [comment]
感谢～具体是在哪一章呀？

**Comment by beeplin** [comment]
https://nomicon.purewhite.io/exotic-sizes.html#%E7%A9%BA%E7%B1%BB%E5%9E%8B

**Comment by PureWhiteWu** [comment]
感谢！专业！
是否方便提一个 PR 修复一下呀～

**Comment by beeplin** [comment]
嗯后面还有几处有问题的，我有空时候统一提pr吧~

nomicon的作者写得英语有点绕，的确容易翻错，要是对rust本身不是那么熟悉的话，的确理解反了都感觉不出来。。。

**Comment by PureWhiteWu** [comment]
感谢指点，翻译的过程确实是，一边要理解 Rust，还要理解英语，有点头大……
