### ISSUE TITLE
repr-rust中的`in-order`翻译错误

### ISSUE THREAD

**Issue by JialuGong** [rust-lang-cn/nomicon-zh-Hans#25]
https://github.com/rust-lang-cn/nomicon-zh-Hans/blob/2312a8f7228523d44d231d407db4d7377ee4dfa4/src/repr-rust.md?plain=1#L52
的原文为
> However with the exception of arrays (which are densely packed and in-order)

其中`in-order`应该是按次序、有序的意思。且结合上下文可知，相较于其它复合解构松散无序的布局， 数组应该相反，是密集有序的。

**Comment by PureWhiteWu** [comment]
抱歉，之前可能 miss 了这个 issue，今天才看到。
非常感谢你的建议，请问你是否有意愿提一个 PR 来修复一下呀？

**Comment by JialuGong** [comment]
> 

好哒，稍候我就去提🙈
