### ISSUE TITLE
书名修改建议

### ISSUE THREAD

**Issue by Faputa** [rust-lang-cn/nomicon-zh-Hans#39]
死灵书这个名字感觉不太恰当，建议改为黑魔法

**Comment by PureWhiteWu** [comment]
https://www.rust-lang.org/zh-CN/learn

你好，这个名字是官方认可的。

![image](https://github.com/rust-lang-cn/nomicon-zh-Hans/assets/3314335/0382f642-7f1e-41d5-a4ee-2cb8b374d9bb)

**Comment by Faputa** [comment]
> https://www.rust-lang.org/zh-CN/learn
> 
> 你好，这个名字是官方认可的。
> 
> ![image](https://private-user-images.githubusercontent.com/3314335/298658158-0382f642-7f1e-41d5-a4ee-2cb8b374d9bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5Nzg5MjEsIm5iZiI6MTcwNTk3ODYyMSwicGF0aCI6Ii8zMzE0MzM1LzI5ODY1ODE1OC0wMzgyZjY0Mi03ZjFlLTQxZDUtYTRlZS0yY2I4YjM3NGQ5YmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjNUMDI1NzAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Nzk3N2EyMWMwMTc4NmRkZjEwY2Q3ZmM3ZmUzYTM1NzMzMzBjMjNjNjgxYmZmMWM3MjU2ZTQzNmE2ZjUzMmU5MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PMKvn-zJuAZwD4pl5Vmqpwg1rR4v85ILpAzcwcWhNFw)

https://github.com/rust-lang/www.rust-lang.org/blame/0b933a84955ad879f79d5a489bbf54b41244bad9/locales/zh-CN/learn.ftl#L45
我看了一下官网的提交记录，这个称谓其实也是国内社区人维护的，我猜想是因为本仓库的翻译是这样子的，类似一个先有鸡还是先有蛋的问题

**Comment by PureWhiteWu** [comment]
你好，这个仓库的翻译是晚于“死灵书”名字出现的，当时选择叫这个名字也是因为官网上名字叫这个。

**Comment by wangl-cc** [comment]
"nonicon" 的词源应该是 "Necronomicon"，而后者通常被翻译为死灵之书。尽管 "dark art" 不等同于 "Necromancy", 但是我觉得这里翻译成死灵书并没有太大问题。
