### ISSUE TITLE
子类型小节的链接有误

### ISSUE THREAD

**Issue by wangl-cc** [rust-lang-cn/nomicon-zh-Hans#40]
应该指向 https://doc.rust-lang.org/reference/subtyping.html#variance 

https://github.com/rust-lang-cn/nomicon-zh-Hans/blob/45ef9f63f384b869cddfde68fa5803b3af1e5349/src/subtyping.md?plain=1#L147-L149

**Comment by PureWhiteWu** [comment]
抱歉，才看到这个 issue。
非常感谢你的反馈，是否有意愿提一个 PR 帮助修复一下呢？
