### ISSUE TITLE
子类型小节翻译修改建议

### ISSUE THREAD

**Issue by kynehc** [rust-lang-cn/nomicon-zh-Hans#47]
原文 “This would be rather unfortunate. In this case, what we want is to accept any type that lives at least as long as 'world. Let's try using subtyping with our lifetimes.“
译文 “ 这是相当不幸的。在这种情况下，我们希望接受的类型的生命周期至少要和 'world 一样长。 让我们尝试使用生命周期进行子类型化。”

“在这种情况下，我们希望接受的类型的生命周期至少要和 'world 一样长。” 这句话读起来有点奇怪，建议可以改为：
“在这种情况下，我们希望接受至少与 'world' 一样长生命周期的任何类型”

**Comment by PureWhiteWu** [comment]
非常感谢你的建议！是否方便直接提个 pr 呀~
